//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasaraGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasaraGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x0001 = !
        ///0x0002 = #
        ///0x0003 = %
        ///0x0004 = &amp;
        ///0x0005 = (
        ///0x0006 = )
        ///0x0007 = *
        ///0x0008 = +
        ///0x0009 = -
        ///0x000A = .
        ///0x000B = /
        ///0x000C = 0
        ///0x000D = 1
        ///0x000E = 2
        ///0x000F = 3
        ///0x0010 = 4
        ///0x0011 = 5
        ///0x0012 = 6
        ///0x0013 = 7
        ///0x0014 = 8
        ///0x0015 = 9
        ///0x0016 = :
        ///0x0017 = =
        ///0x0018 = A
        ///0x0019 = B
        ///0x001A = C
        ///0x001B = D
        ///0x001C = E
        ///0x001D = F
        ///0x001E = H
        ///0x001F = K
        ///0x0020 = L
        ///0x0021 = M
        ///0x0022 = O
        ///0x0023 = P
        ///0x0024 = R
        ///0x0025 = S
        ///0x0026 = T
        ///0x0027 = U
        ///0x0028 = V
        ///0x0029 = X
        ///0x002A = Y
        ///0x002B = [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TableStrings {
            get {
                return ResourceManager.GetString("TableStrings", resourceCulture);
            }
        }
    }
}
